### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [comitechampagne/PhysiocapCIVC#1]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by pcav** [comment]
@comitechampagne could you please fix this, so that I can publish your plugin?
Thanks.

**Comment by comitechampagne** [comment]
unecessary files were deleted. is there any way to delete a repository inside the main one ? Thanks

**Comment by pcav** [comment]
Sorry, I don't understand your question.
